name: Deploy Project

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key manually
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa  # Add SSH private key from GitHub Secrets
          chmod 600 ~/.ssh/id_rsa  # Set proper permissions on the private key file

          # Add GitHub's SSH keys to known hosts to avoid authenticity prompts
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Deploy files to VPS using SCP
        run: |
          # Set the VPS details
          VPS_USER="root"
          VPS_HOST="your_vps_ip_or_hostname"
          VPS_DIR="/opt/docker_containers/web/matthijsverheijen.com/test/html"

          # Use SCP to copy files to the VPS
          scp -r -i ${{ secrets.SSH_PRIVATE_KEY }} -o StrictHostKeyChecking=no ./ $VPS_USER@$VPS_HOST:$VPS_DIR
