name: Deploy Project

on:
  push:
    branches:
      - master

jobs:
  deploy-via-sftp:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: actions/checkout@v3
      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.1
        with:
          username: root
          server: matthijsverheijen.com
          port: 22 # default is 22
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: ./*
          remote_path: /opt/docker_containers/web/matthijsverheijen.com/test/html
          args: "-o ConnectTimeout=5"
