name: Deploy Project

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client
          mkdir -p ~/.ssh
          eval $(ssh-agent -s)
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Test SSH connection
        run: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 22 root@matthijsverheijen.com 'echo connected'

      - name: Deploy via rsync
        run: |
          rsync -avz --delete --exclude ".*" --exclude "README.md" -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 22" ./ root@matthijsverheijen.com:/opt/docker_containers/web/matthijsverheijen.com/test/html

    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    # Optional: Define an environment for deployment, like production
    environment:
      name: production
      url: https://test.matthijsverheijen.com
